### ISSUE TITLE
where is the attention mechanism?

### ISSUE THREAD

**Issue by sxzy** [brandontrabucco/detailed_captioning#1]
I didn't find the attention part can you figure it out ?

**Comment by brandontrabucco** [comment]
Hi Katherine, thanks for reading my code! The answer to your question depends on which attention mechanism you are referring to.

In the file [up_down_cell.py](https://github.com/brandontrabucco/detailed_captioning/blob/199b768be84bcb4db4951f60708e97c8f164b761/detailed_captioning/cells/up_down_cell.py) I implement the attention mechanism from [this paper](https://arxiv.org/abs/1707.07998).

In order to train this model, you must first download and process the MSCOCO dataset using the scripts located in [this folder](https://github.com/brandontrabucco/detailed_captioning/tree/199b768be84bcb4db4951f60708e97c8f164b761/data).

Assuming you have access to a GPU, you can train the model by running [this python](https://github.com/brandontrabucco/detailed_captioning/blob/199b768be84bcb4db4951f60708e97c8f164b761/scripts/train/train_up_down.py) script.

The code should work as is, but I am still making changes, adding my own research contributions, and making the training faster.

Also, my code depends on some other repositories: my implementation of [glove word vectors](https://github.com/brandontrabucco/glove/tree/3d9cb98573119b0a3d1f3e6405881b9156ad9421), and [TensorFlow object detection ](https://github.com/tensorflow/models/tree/b2522f9bb9a559e148502a67ebd9a6592320cb0f/research/object_detection).

**Comment by sxzy** [comment]
> Hi Katherine, thanks for reading my code! The answer to your question depends on which attention mechanism you are referring to.
> 
> In the file [up_down_cell.py](https://github.com/brandontrabucco/detailed_captioning/blob/199b768be84bcb4db4951f60708e97c8f164b761/detailed_captioning/cells/up_down_cell.py) I implement the attention mechanism from [this paper](https://arxiv.org/abs/1707.07998).
> 
> In order to train this model, you must first download and process the MSCOCO dataset using the scripts located in [this folder](https://github.com/brandontrabucco/detailed_captioning/tree/199b768be84bcb4db4951f60708e97c8f164b761/data).
> 
> Assuming you have access to a GPU, you can train the model by running [this python](https://github.com/brandontrabucco/detailed_captioning/blob/199b768be84bcb4db4951f60708e97c8f164b761/scripts/train/train_up_down.py) script.
> 
> The code should work as is, but I am still making changes, adding my own research contributions, and making the training faster.
> 
> Also, my code depends on some other repositories: my implementation of [glove word vectors](https://github.com/brandontrabucco/glove/tree/3d9cb98573119b0a3d1f3e6405881b9156ad9421), and [TensorFlow object detection ](https://github.com/tensorflow/models/tree/b2522f9bb9a559e148502a67ebd9a6592320cb0f/research/object_detection).

Thanks~~~~~~~~~~~~~~
